#pragma once
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <conio.h>
#include "database.h"
#include "bus.h"
#include "line.h"
#include "station.h"
#include "power.h"
#include "role.h"
#include "user.h"
#include "schedule.h"
#include "line_station.h"
#include "role_power.h"
#include "menu.h"
#include "menu1.h"
#include "menu2.h"
#include "menu3.h"
#include "menu4.h"
#include "menu3_1.h"
#include "menu3_2.h"
#include "menu3_3.h"
#include "menu3_4.h"
#include "menu3_5.h"
#include "validation.h"


void menu();
void menu1();
void menu2();
void menu3();
void menu4();
void menu3_1();
void menu3_2();
void menu3_3();
void menu3_4();
void menu3_5();
